# Generated by Django 3.2.12 on 2023-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQ1_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table5',
            name='visitID',
            field=models.CharField(max_length=50),
        ),
    ]
