# Generated by Django 3.2.12 on 2023-03-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DQ1_app', '0002_alter_table5_visitid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table5',
            new_name='TableA',
        ),
    ]
